import React from "react";
import "./Services.scss";
import img from "../../assets/solar1.avif"
import Indicator from "../../components/indicator/Indicator";
import PageTop from "../../components/page-top/PageTop";

const servicesData = [
    {
        title: "Solar ",
        title1: "Energy",
        description: "Solar energy is one of the most abundant and clean sources of renewable energy. By capturing sunlight using photovoltaic panels, we generate electricity without polluting the environment. Solar power reduces carbon emissions, lowers electricity bills, and supports sustainable living.",
        image: img
    },
    {
        title: "Wind",
        title1: "Energy",
        description: "Wind energy harnesses the power of moving air to generate electricity. Modern wind turbines convert wind into clean and renewable energy that can power homes, industries, and communities. It plays a vital role in reducing reliance on fossil fuels.",
        image: img,
    },
    {
        title: "Tidal",
        title1: "Energy",
        description: "Tidal energy uses the natural rise and fall of ocean tides to produce electricity. It is predictable and reliable compared to other renewable sources. With advancements in technology, tidal power is becoming a sustainable option for coastal regions.",
        image: img,
    },
    {
        title: "Hydroelectric",
        title1: "Energy",
        description: "Hydroelectric energy is generated by converting the flow of water into electricity. Dams and hydro plants provide clean, renewable, and cost-effective power while also supporting irrigation and flood control. It remains one of the oldest and most reliable renewable sources.",
        image: img,
    },
    {
        title: "Hydrogen & electric charging station ",
        title1: " powered by renewable energy",
        description: "Hydrogen fuel cells and renewable-powered EV charging stations are the future of clean transportation. By using renewable energy sources like solar and wind, we can create sustainable charging infrastructure and reduce dependency on fossil fuels.",
        image: img,
    },
];

function Services() {
    return (
        <>
        <PageTop text="Our" subText="Services" />
            <>
                <div className="services-header">
                    <Indicator text="Our Services" bg="var(--green)" />
                    <h3><span>What do</span> <span className="highlight">we Offer</span></h3>
                </div>
                {servicesData.map((service, index) => (
                    <div
                        key={index}
                        className={`parent-service ${index % 2 === 1 ? "grey-bg" : ""}`}
                    >
                        <div className={`container cont-service ${index % 2 === 1 ? "reverse" : ""}`}>
                            <div className="left-right">
                                <div className="left">
                                    <h3>
                                        <span>{service.title}</span> <span className="highlight">{service.title1}</span>
                                    </h3>
                                    <p>{service.description}</p>
                                </div>
                                <div className="right">
                                    <img src={service.image} alt={service.title} />
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
            </>
        </>
    );
}

export default Services;
